"""Central configuration for ASTRA.

Single source of truth for every path, threshold, weight, and multiplier used
across the data, scoring, ML, and engine layers. Nothing domain-specific should
be hardcoded elsewhere — import from here so the whole system stays consistent
and is trivially tunable.
"""

from __future__ import annotations

from pathlib import Path

# ─────────────────────────────────────────────────────────────────────────────
# Paths
# ─────────────────────────────────────────────────────────────────────────────
ROOT = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv

    load_dotenv(ROOT / ".env")
except Exception:
    pass

DATA_DIR = ROOT / "data"
RAW_DIR = DATA_DIR / "raw"
INTERIM_DIR = DATA_DIR / "interim"
PROCESSED_DIR = DATA_DIR / "processed"
ARTIFACTS_DIR = ROOT / "artifacts"

RAW_EVENTS_CSV = RAW_DIR / "astra_events.csv"

# Processed outputs (regenerated by the pipeline scripts)
EVENTS_CLEAN = PROCESSED_DIR / "events_clean.parquet"
EVENTS_SCORED = PROCESSED_DIR / "events_scored.parquet"
JUNCTION_REGISTRY = PROCESSED_DIR / "junction_registry.parquet"
JUNCTION_RISK = PROCESSED_DIR / "junction_risk.parquet"
ZONE_RISK = PROCESSED_DIR / "zone_risk.parquet"
CORRIDOR_RISK = PROCESSED_DIR / "corridor_risk.parquet"
JUNCTION_DISTANCES = PROCESSED_DIR / "junction_distances.parquet"

# Model artifacts
DURATION_MODEL = ARTIFACTS_DIR / "duration_model.joblib"
DURATION_METRICS = ARTIFACTS_DIR / "duration_metrics.json"
DURATION_IMPORTANCE = ARTIFACTS_DIR / "duration_feature_importance.json"

# ─────────────────────────────────────────────────────────────────────────────
# Earth / geometry
# ─────────────────────────────────────────────────────────────────────────────
EARTH_RADIUS_KM = 6371.0

# Bangalore is ~40 km across — a single event cannot gridlock a quarter of the
# city, so impact radius is capped here.
MAX_IMPACT_RADIUS_KM = 10.0

# Start/end coordinate spans above this are coordinate corruption (the 99th pct
# of legitimate spans is ~6.6 km; corrupt rows jump straight to 100s+ km).
SPAN_CORRUPTION_KM = 10.0

# ─────────────────────────────────────────────────────────────────────────────
# Time conventions
# ─────────────────────────────────────────────────────────────────────────────
PEAK_HOURS = {8, 9, 10, 17, 18, 19, 20}          # morning + evening commute
NIGHT_HOURS = {0, 1, 2, 3, 4, 5, 6, 22, 23}
WEEKEND_TIME_FACTOR = 0.6                          # traffic is materially lower

# Duration cleaning bounds (hours)
DURATION_MIN_HOURS = 0.0      # exclusive — drop <= 0 (closed before/at start)
DURATION_MAX_HOURS = 168.0    # 7 days — above this is a stale/bulk-closed ticket

# ─────────────────────────────────────────────────────────────────────────────
# ESI — Event Severity Index (0–100), 5 weighted rule-based components
# ─────────────────────────────────────────────────────────────────────────────
ESI_WEIGHTS = {
    "cause": 0.30,
    "duration": 0.25,
    "closure": 0.20,
    "time": 0.15,
    "junction": 0.10,
}

# Canonical cause normalization. Raw data has case variants and extra labels
# ('Debris'/'debris', 'Fog / Low Visibility', 'others', 'test_demo') — map every
# raw value onto a canonical key so no cause silently falls through to a default.
CAUSE_NORMALIZE = {
    "debris": "debris",
    "fog / low visibility": "fog_low_visibility",
    "fog/low visibility": "fog_low_visibility",
    "others": "others",
    "test_demo": "test_demo",
}

# S_cause — severity by event cause (disruption intensity, not just duration)
CAUSE_SCORE = {
    "vehicle_breakdown": 15,
    "accident": 25,
    "congestion": 35,
    "procession": 40,
    "fog_low_visibility": 45,   # reduces capacity broadly, rarely full blockage
    "vip_movement": 50,
    "public_event": 50,
    "debris": 50,               # obstruction; needs clearing crew
    "protest": 55,
    "tree_fall": 55,
    "pot_holes": 60,
    "road_conditions": 65,
    "construction": 70,
    "water_logging": 85,
    "others": 40,               # unknown — neutral midpoint
    "test_demo": 5,             # test entries — negligible
}
CAUSE_SCORE_DEFAULT = 40

# S_duration — breakpoints derived from the duration percentile distribution
# Each tuple is (upper_bound_hours_exclusive, score). Last bucket is the catch-all.
DURATION_SCORE_BANDS = [
    (0.5, 10),
    (1.0, 25),
    (3.0, 45),
    (6.0, 60),
    (12.0, 75),
    (24.0, 85),
    (float("inf"), 95),
]

# S_time — by hour of day (Bangalore traffic volume profile)
def time_score(hour: int) -> int:
    if 17 <= hour <= 20:
        return 100      # evening peak — worst
    if 8 <= hour <= 10:
        return 90       # morning peak
    if hour in (7, 16):
        return 60       # pre-peak ramp-up
    if 11 <= hour <= 15:
        return 30       # off-peak daytime
    if 21 <= hour <= 22:
        return 20       # post-peak wind-down
    return 5            # night (23–06)

# ESI → risk label thresholds
RISK_BANDS = [
    (30, "LOW"),
    (60, "MEDIUM"),
    (80, "HIGH"),
    (100, "CRITICAL"),
]
RISK_COLORS = {
    "LOW": "#22c55e",
    "MEDIUM": "#eab308",
    "HIGH": "#f97316",
    "CRITICAL": "#ef4444",
}

# ─────────────────────────────────────────────────────────────────────────────
# Impact radius — base(duration) × M_closure × M_peak × M_cause, capped
# ─────────────────────────────────────────────────────────────────────────────
# base radius (km) by duration band: (upper_bound_hours_exclusive, base_km)
IMPACT_BASE_BANDS = [
    (0.5, 0.3),
    (1.0, 0.8),
    (3.0, 1.5),
    (6.0, 3.0),
    (12.0, 5.0),
    (float("inf"), 7.0),
]
IMPACT_CLOSURE_MULT = 1.8       # full closure forces 100% rerouting
IMPACT_PEAK_MULT = 1.6          # same blockage displaces far more vehicles
IMPACT_CAUSE_MULT = {
    "vehicle_breakdown": 1.0,
    "test_demo": 1.0,
    "others": 1.0,
    "congestion": 1.2,
    "accident": 1.2,
    "fog_low_visibility": 1.2,
    "pot_holes": 1.3,
    "tree_fall": 1.3,
    "debris": 1.3,
    "construction": 1.4,
    "procession": 1.4,
    "water_logging": 1.5,
    "public_event": 1.5,
    "vip_movement": 1.5,
    "protest": 1.6,
}
IMPACT_CAUSE_MULT_DEFAULT = 1.0

# Concentric ring boundaries as fractions of the impact radius
RING_INNER_FRAC = 1 / 3         # 0 .. 1/3 → HIGH (red)
RING_MIDDLE_FRAC = 2 / 3        # 1/3 .. 2/3 → MEDIUM (orange)
# 2/3 .. 1.0 → LOW (yellow)

# ─────────────────────────────────────────────────────────────────────────────
# Spillover propagation graph
# ─────────────────────────────────────────────────────────────────────────────
EDGE_SAME_CORRIDOR_KM = 3.0     # Rule A: same corridor & within this distance
EDGE_CROSS_CORRIDOR_KM = 1.5    # Rule B: different corridors, must be intersecting
CORRIDOR_FACTOR_SAME = 0.5      # congestion flows freely along one road
CORRIDOR_FACTOR_CROSS = 1.0     # must "turn a corner" to spread
DECAY_KAPPA = 2.0               # exponential decay constant
PROPAGATION_THRESHOLD = 0.10    # stop when congestion drops below 10%
ETA_MIN_PER_COST = 8.0          # minutes of spread per unit of propagation cost

# Junction risk score weights (frequency dominates)
JUNCTION_RISK_WEIGHTS = {
    "incident_count": 0.4,
    "avg_duration": 0.3,
    "road_closure_rate": 0.3,
}

# Congestion level → risk label (spillover graph)
SPILLOVER_HIGH = 0.60
SPILLOVER_MEDIUM = 0.30

# ─────────────────────────────────────────────────────────────────────────────
# Similar event engine — weighted k-NN
# ─────────────────────────────────────────────────────────────────────────────
SIMILARITY_WEIGHTS = {
    "cause": 0.35,
    "location": 0.25,
    "closure": 0.20,
    "hour": 0.12,
    "weekday": 0.08,
}
SIMILARITY_LOCATION_NORM_KM = 10.0   # events >= 10 km apart → max location distance
SIMILARITY_HOUR_NORM = 12.0          # max circular hour distance
SIMILARITY_WEEKDAY_NORM = 3.5        # max circular weekday distance
SIMILAR_K = 15                        # neighbours to retrieve
SIMILARITY_THRESHOLD = 0.40          # exclude matches with distance above this

# Confidence factor weights
CONFIDENCE_WEIGHTS = {"match_count": 0.4, "consistency": 0.4, "alignment": 0.2}

# ─────────────────────────────────────────────────────────────────────────────
# Diversion engine
# ─────────────────────────────────────────────────────────────────────────────
DIVERSION_CORRIDOR_WEIGHTS = {"load": 0.4, "reliability": 0.3, "capacity": 0.3}
DIVERSION_CANDIDATE_RADIUS_MULT = 2.0   # candidate must be within 2× impact radius
DIVERSION_CONFIDENCE_WEIGHTS = {
    "corridor_score": 0.30,
    "historical_success": 0.25,
    "spillover_safety": 0.20,
    "proximity": 0.15,
    "similarity_count": 0.10,
}

# ─────────────────────────────────────────────────────────────────────────────
# Resource planner
# ─────────────────────────────────────────────────────────────────────────────
OFFICERS_PER_HIGH_JUNCTION = 2
OFFICERS_PER_MEDIUM_JUNCTION = 1
OFFICERS_PER_LOW_JUNCTION = 0
PERIMETER_KM_PER_OFFICER = 1.5
SITE_OFFICERS = {
    "vehicle_breakdown": 1,
    "pot_holes": 1,
    "road_conditions": 1,
    "test_demo": 1,
    "others": 1,
    "fog_low_visibility": 1,
    "tree_fall": 2,
    "construction": 2,
    "water_logging": 2,
    "congestion": 2,
    "debris": 2,
    "accident": 3,
    "procession": 4,
    "public_event": 5,
    "vip_movement": 6,
    "protest": 6,
}
SITE_OFFICERS_DEFAULT = 2
TOTAL_POLICE_CAP = 50
SITE_BARRICADES_CLOSURE = 4
SITE_BARRICADES_OPEN = 1
DIVERSION_BARRICADES_PER_KM = 4
PATROL_SQKM_PER_VEHICLE = 8.0
PATROL_LONG_DURATION_HOURS = 8.0
PATROL_VEHICLE_CAP = 8
MAJOR_CORRIDORS = {"ORR", "Hosur Road", "Bellary Road"}
MAJOR_CORRIDOR_IMPORTANCE = 1.5
DEFAULT_CORRIDOR_IMPORTANCE = 1.0

# ─────────────────────────────────────────────────────────────────────────────
# External APIs (MapMyIndia) — optional; system runs fully on Haversine if absent
# ─────────────────────────────────────────────────────────────────────────────
PEAK_TRAVEL_TIME_FACTOR = 1.4   # peak-hour adjustment for API travel times
